"""added name column to tag table

Revision ID: 255aef372081
Revises: 4a537290633d
Create Date: 2020-12-19 15:24:54.902037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255aef372081'
down_revision = '4a537290633d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###
